---
- hosts: localhost

  roles:
    # setup the common environment files
    - role: '../dotfiles'

    # setup the homebrew, caskroom, gems configuration
    - role: osx.homebrew
      when: ansible_distribution == 'MacOSX'

  tasks:

    - meta: flush_handlers

    # install all Brew apps
    - name: copy over Brewfile
      copy: src=files/Brewfile dest=/tmp/Brewfile
      register: brewfile
      
    - name: install applications from Brewfile
      shell: brew brewdle chdir=/tmp/
      when: brewfile.changed

    # configure all osx defaults
    - name: install osx defaults
      copy: src=files/osx-defaults.sh dest=/tmp/osx-defaults.sh mode=0755
      register: osx_defaults

    - name: run defaults
      command: /tmp/osx-defaults.sh
      register: osx_defaults.changed
    
    # configure zsh
    - name: configure zsh, if installed
      stat: path=/usr/local/bin/zsh
      register: zsh_installed

    - name: add homebrew zsh to /etc/shells
      sudo: yes
      lineinfile: dest=/etc/shells
                  regexp="local"
                  line="/usr/local/bin/zsh"
                  state=present
      when: zsh_installed.stat.exists == true

    - name: set zsh as default shell
      shell: chsh -s /usr/local/bin/zsh
      when: zsh_installed.stat.exists == true

    # configure zsh
    - name: install the zsh configuration
      shell: ./setup.zsh chdir={{ ansible_env.PWD }}/files/zsh
    
    # link emacs
    - name: link the emacs configuration
      file: src={{ ansible_env.PWD }}/files/emacs.d dest=/Users/mahmoud/.emacs.d/ state=link
