# -*- mode: ruby -*-
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'homebrew/dupes'

brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'pstree'
brew 'zsh'
brew 'git'
brew 'hub'
brew 'curl'
brew 'autoconf'
brew 'automake'
brew 'gawk'
brew 'openssl'
brew 'tree'
brew 'readline'
brew 'docker'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'reattach-to-user-namespace'
brew 'zlib'
brew 'tmux'
brew 'z'
brew 'gettext'
brew 'mackup'
brew 'python', args: ['--framework']
brew 'rbenv', args: ['--HEAD']
brew 'ruby-build'
brew 'gnu-sed', args: ['--with-default-names']
brew 'bash'
brew 'bash-completion'
brew 'wget', args: ['--with-iri']
brew 'p7zip'
brew 'ssh-copy-id'
brew 'emacs'
brew 'jq'
brew 'go', args: ['--with-cc-common']
brew 'unison'

# brew 'emacs', args: ['cocoa', 'srgb', 'with-gnutls']

# mac apps
cask 'google-chrome'
cask 'dropbox'
cask 'monotype-skyfonts'
cask 'spotify'
cask 'skitch'
cask 'iterm2-nightly'
cask 'skitch'
cask '1password'
cask 'seil'
cask 'heroku-toolbelt'
cask 'font-dejavu-sans'
cask 'font-inconsolata'
cask 'colors'
cask 'karabiner'
cask 'sizeup'
cask 'little-snitch'
cask 'bartender'
cask 'caffeine'
cask 'dash'
cask 'istat-menus'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'skim'
cask 'slack'
cask 'evernote'

# vagrant & virtualbox
cask 'virtualbox4330101610'
cask 'vagrant'

# java..because
cask 'java'
brew 'maven'
cask 'intellij-idea'
